=== rizalgowandy/octocov/report/custom_metrics_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "key": {
            "type": "string",
            "minLength": 1
        },
        "name": {
            "type": "string",
            "minLength": 1
        },
        "metadata": {
            "type": "array",
            "items":
            {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string",
                        "minLength": 1
                    },
                    "name": {
                        "type": "string",
                        "minLength": 1
                    },
                    "value": {
                        "type": "string"
                    }
                },
                "required": [
                    "key",
                    "value"
                ]
            }
        },
        "metrics": {
            "type": "array",
            "items":
            {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string",
                        "minLength": 1
                    },
                    "name": {
                        "type": "string",
                        "minLength": 1
                    },
                    "value": {
                        "type": "number"
                    },
                    "unit": {
                        "type": "string",
                        "minLength": 1
                    }
                },
                "required": [
                    "key",
                    "value"
                ]
            },
            "minItems": 1
        }
    },
    "required": [
        "key",
        "metrics"
    ]
}

=== rizalgowandy/octocov/testdata/custom_metrics/benchmark_0.json
{
  "key": "benchmark_0",
  "name": "Benchmark-0 (this is custom metrics test)",
  "metadata": [
    {
      "key": "goos",
      "name": "GOOS",
      "value": "darwin"
    },
    {
      "key": "goarch",
      "name": "GOARCH",
      "value": "amd64"
    }
  ],
  "metrics": [
    {
      "key": "N",
      "name": "Number of iterations",
      "value": 1000
    },
    {
      "key": "NsPerOp",
      "name": "Nanoseconds per iteration",
      "value": 676.5,
      "unit": " ns/op"
    }
  ]
}
